### ISSUE TITLE
Two labels with description above the table.

### ISSUE THREAD

**Issue by manamski** [PejmanNik/ExcelToLaravelSeeder#1]
Hey.
Thank you very much for this application - helped me a lot.
But when I first start the application I entered "Excel File" and "WorkSheet Index", I clicked "Read File" and did not know what to type in the table.
Could you put above the table two labels such as "Excel column:" (above left column of the table) and "Output field name:" (above right column) or something like that?
Regards,
Piotr.

**Comment by PejmanNik** [comment]
Hello
Thank you for using that, glad to hear that was useful for you.
yes i do it and you can test it now :)
