### ISSUE TITLE
Not Strating From 0 Index

### ISSUE THREAD

**Issue by zymawy** [PejmanNik/ExcelToLaravelSeeder#2]
Nice App For Real 

I have an issue  , This is my csv 

**id , name , email , test** 

when using app result being like this 

`
User::create([
'id' => 'name',
'name' => 'email',
'email' => 'test',
 ]);

User::create([
'id' => 'hamza',
'name' => 'zymawy@gmail.com',
'email' => '',
 ]);

User::create([
'id' => 'mallam',
'name' => 'zymawy@gmail.com',
'email' => '',
 ]);

User::create([
'id' => 'musa',
'name' => 'zymawy@gmail.com',
'email' => '',
 ]);

User::create([
'id' => 'mohmmad',
'name' => 'zymawy@gmail.com',
'email' => '',
 ]);

User::create([
'id' => 'zymawy',
'name' => 'zymawy@gmail.com',
'email' => '',
 ]);
`

there is a miss assigning  

id not assigning to id it's assiging  to name vaule instead !! 

the 

> WorkSheet Index : Is 1 In my case cus it's the only index is working 

thx for great work

**Comment by PejmanNik** [comment]
Hello thank you for using this tool
I test it and don't see this problem, please send your file (2 row is enough) for testing
